fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: ArtesanIO\ArtesanusBundle\Entity\User
    group:
        group_class: ArtesanIO\ArtesanusBundle\Entity\Group
        form:
            type: artesanio_user_group
    profile:
        form:
            type: artesanio_user_profile
