services:

    artesanio.usuarios_manager:
        class: ArtesanIO\ArtesanusBundle\Model\UsuariosManager
        arguments:
            - @doctrine.orm.entity_manager
            - ArtesanIO\ArtesanusBundle\Entity\Usuarios
            - @artesanio.encoder

    artesanio.grupos_manager:
        class: ArtesanIO\ArtesanusBundle\Model\GruposManager
        arguments:
            - @doctrine.orm.entity_manager
            - ArtesanIO\ArtesanusBundle\Entity\Grupos

    artesanio.roles_manager:
        class: ArtesanIO\ArtesanusBundle\Model\RolesManager
        arguments:
            - @doctrine.orm.entity_manager
            - ArtesanIO\ArtesanusBundle\Entity\Roles
            - @artesanio.sluger_role
