services:

    artesanus.user_manager:
        class: ArtesanIO\ArtesanusBundle\Model\UserManager
        arguments:
            - @doctrine.orm.entity_manager
            - ArtesanIO\ArtesanusBundle\Entity\User
            - @artesanio.encoder

    artesanus.group_manager:
        class: ArtesanIO\ArtesanusBundle\Model\GroupManager
        arguments:
            - @doctrine.orm.entity_manager
            - ArtesanIO\ArtesanusBundle\Entity\Group

    artesanus.roles_manager:
        class: ArtesanIO\ArtesanusBundle\Model\RolesManager
        arguments:
            - @doctrine.orm.entity_manager
            - ArtesanIO\ArtesanusBundle\Entity\Roles
            - @artesanus.sluger_role
