acl:
    resource: "@ArtesanusBundle/Resources/config/routing/acl.yml"
    prefix: /acl

# login:
#     pattern:   /login
#     defaults:  { _controller: ACLBundle:Security:login }
#
# login_check:
#     pattern:   /login_check
