services:

    artesanio.usuarios_provider:
        class:  ArtesanIO\ACLBundle\Security\UsuariosProvider
        arguments:
            - @artesanio.usuarios_manager

    artesanio.encoder:
        class:  ArtesanIO\ACLBundle\Utils\Encoder
        arguments:
            - @security.encoder_factory

    artesanio.sluger_role:
        class:  ArtesanIO\ACLBundle\Utils\SlugerRole

    artesanio.profile.form.type:
        class: ArtesanIO\ACLBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: artesanio_user_profile }

    artesanio.group.form.type:
        class: ArtesanIO\ACLBundle\Form\Type\GroupFormType
        tags:
            - { name: form.type, alias: artesanio_user_group }
