services:

    artesanio.encoder:
        class:  ArtesanIO\ArtesanusBundle\Utils\Encoder
        arguments:
            - @security.encoder_factory

    artesanus.sluger_role:
        class:  ArtesanIO\ArtesanusBundle\Utils\SlugerRole

    artesanio.profile.form.type:
        class: ArtesanIO\ACLBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: artesanio_user_profile }

    artesanio.group.form.type:
        class: ArtesanIO\ACLBundle\Form\Type\GroupFormType
        tags:
            - { name: form.type, alias: artesanio_user_group }
